import { describe, expect, it, vi } from "vitest";
import type { VibecoreManifest } from "@vibecore/contracts";
import { createRailwayDeploymentPlan, executeRailwayDeploymentPlan, type RailwayCommandRunner } from "./railway.js";

const revision = "abcdef1234567890abcdef1234567890abcdef12";
const manifest: VibecoreManifest = { apiVersion: "vibecore.dev/v1alpha1", kind: "Application", metadata: { name: "app" }, applications: { api: { type: "api", framework: "hono", language: "typescript", path: "apps/api", commands: { start: "node dist/index.js" }, health: { path: "/health" } } }, variables: { DATABASE_URL: { required: true, secret: true, applications: ["api"] } }, environments: { dev: { runtime: "local-process" }, staging: { runtime: "railway" }, production: { runtime: "railway", production: true } } };

class RailwayRunner implements RailwayCommandRunner {
  calls: Array<{ command: string; args: string[]; token?: string }> = [];
  constructor(private readonly head = revision, private readonly dirty = "") {}
  async run(command: string, args: string[], options?: { env?: NodeJS.ProcessEnv }) { this.calls.push({ command, args, ...(options?.env?.RAILWAY_TOKEN ? { token: options.env.RAILWAY_TOKEN } : {}) }); if (command === "git" && args[0] === "rev-parse") return { exitCode: 0, stdout: `${this.head}\n`, stderr: "" }; if (command === "git" && args[0] === "status") return { exitCode: 0, stdout: this.dirty, stderr: "" }; return { exitCode: 0, stdout: "{}\n", stderr: "" }; }
}

describe("Railway deployment", () => {
  it("creates a token-free immutable plan", () => { const plan = createRailwayDeploymentPlan(manifest, { application: "api", environment: "staging", sourceRevision: revision, mode: "git", project: "project-id", service: "api", healthUrl: "https://api.example.com/health" }); expect(plan).toMatchObject({ provider: "railway", project: "project-id", service: "api", railwayEnvironment: "staging", requiredSecretNames: ["DATABASE_URL", "RAILWAY_TOKEN"] }); expect(JSON.stringify(plan)).not.toContain("token-value"); });
  it("requires exact and separate production approval before commands", async () => { const plan = createRailwayDeploymentPlan(manifest, { application: "api", environment: "production", sourceRevision: revision, mode: "git", project: "project-id", service: "api", healthUrl: "https://api.example.com/health" }); const runner = new RailwayRunner(); await expect(executeRailwayDeploymentPlan(plan, { approval: "wrong", repositoryRoot: "/repo", token: "token-value", runner })).rejects.toThrow("approval"); await expect(executeRailwayDeploymentPlan(plan, { approval: plan.digest, repositoryRoot: "/repo", token: "token-value", runner })).rejects.toThrow("production approval"); expect(runner.calls).toHaveLength(0); });
  it("verifies HEAD and clean application files before non-interactive deployment", async () => { const plan = createRailwayDeploymentPlan(manifest, { application: "api", environment: "staging", sourceRevision: revision, mode: "git", project: "project-id", service: "api", healthUrl: "https://api.example.com/health" }); const dirty = new RailwayRunner(revision, " M apps/api/index.ts"); await expect(executeRailwayDeploymentPlan(plan, { approval: plan.digest, repositoryRoot: "/repo", token: "token-value", runner: dirty })).rejects.toThrow("changed"); expect(dirty.calls.some(({ command }) => command === "railway")).toBe(false); });
  it("passes the token only through environment and records external health", async () => { const plan = createRailwayDeploymentPlan(manifest, { application: "api", environment: "staging", sourceRevision: revision, mode: "git", project: "project-id", service: "api", healthUrl: "https://api.example.com/health" }); const runner = new RailwayRunner(); const result = await executeRailwayDeploymentPlan(plan, { approval: plan.digest, repositoryRoot: "/repo", token: "token-value", runner, healthFetch: vi.fn().mockResolvedValue(new Response("ignored", { status: 200 })) }); const railway = runner.calls.find(({ command }) => command === "railway"); expect(railway?.args).toEqual(["up", "apps/api", "--path-as-root", "--ci", "--json", "--project", "project-id", "--environment", "staging", "--service", "api", "--message", `vibecore ${revision}`]); expect(railway?.args.join(" ")).not.toContain("token-value"); expect(railway?.token).toBe("token-value"); expect(result.release).toMatchObject({ provider: "railway", status: "healthy", sourceRevision: revision }); expect(JSON.stringify(result)).not.toContain("token-value"); });
});
