import { describe, expect, it, vi } from "vitest";
import type { DeploymentConfigurationPlan, Release } from "@vibecore/contracts";
import { applyHealthResult, createRelease, createRollbackPlan, recordRollback, verifyDeploymentHealth } from "./releases.js";

const plan: DeploymentConfigurationPlan = { provider: "railway", application: "api", environment: "staging", sourceRevision: "abcdef1234567", digest: "plan-digest", files: [], requiredSecretNames: ["DATABASE_URL"], notes: [] };
const release = (overrides: Partial<Release>): Release => ({ id: "release-default", application: "api", provider: "railway", mode: "git", environment: "staging", sourceRevision: "abcdef1234567", planDigest: "digest", status: "healthy", createdAt: "2026-08-20T00:00:00.000Z", updatedAt: "2026-08-20T00:00:00.000Z", ...overrides });

describe("deployment release lifecycle", () => {
  it("creates a secret-free release bound to a plan", () => { const value = createRelease(plan, "git", new Date("2026-08-21T00:00:00.000Z")); expect(value).toMatchObject({ provider: "railway", mode: "git", sourceRevision: "abcdef1234567", status: "deploying" }); expect(JSON.stringify(value)).not.toContain("DATABASE_URL"); });
  it("retries health checks and records bounded evidence", async () => { const request = vi.fn().mockResolvedValueOnce(new Response("no", { status: 503 })).mockResolvedValueOnce(new Response("ok", { status: 200 })); const health = await verifyDeploymentHealth("https://example.com/health#ignored", { attempts: 2, intervalMs: 0, fetch: request }); expect(health).toMatchObject({ url: "https://example.com/health", status: "healthy", attempts: 2, statusCode: 200 }); expect(applyHealthResult(release({ status: "deploying" }), health).status).toBe("healthy"); });
  it("does not follow health redirects or accept credential-bearing URLs", async () => { const request = vi.fn().mockResolvedValue(new Response(null, { status: 302 })); const result = await verifyDeploymentHealth("https://example.com/health", { attempts: 1, intervalMs: 0, fetch: request }); expect(result).toMatchObject({ status: "unhealthy", errorCode: "HEALTH_HTTP_STATUS" }); expect(request.mock.calls[0]?.[1]).toMatchObject({ redirect: "error" }); await expect(verifyDeploymentHealth("https://user:secret@example.com", { attempts: 1, fetch: request })).rejects.toThrow("credentials"); });
  it("plans rollback only to the preceding healthy matching release and requires exact approval", () => { const healthy = release({ id: "release-good", sourceRevision: "1111111", createdAt: "2026-08-20T00:00:00.000Z" }); const failed = release({ id: "release-bad", sourceRevision: "2222222", status: "unhealthy", createdAt: "2026-08-21T00:00:00.000Z", updatedAt: "2026-08-21T00:00:00.000Z" }); const rollback = createRollbackPlan([failed, healthy], failed.id); expect(rollback.targetReleaseId).toBe(healthy.id); expect(() => recordRollback([failed, healthy], rollback, "wrong")).toThrow("approval"); const recorded = recordRollback([failed, healthy], rollback, rollback.digest, new Date("2026-08-21T01:00:00.000Z")); expect(recorded.failed.status).toBe("rolled-back"); expect(recorded.rollback).toMatchObject({ sourceRevision: "1111111", status: "deploying", rollbackOf: "release-bad" }); });
});
