import { describe, expect, it, vi } from "vitest";
import type { VibecoreManifest } from "@vibecore/contracts";
import { createRollbackPlan } from "./releases.js";
import { createSelfHostedDockerPlan, executeSelfHostedDockerPlan, executeSelfHostedRollback, type DeploymentCommandRunner } from "./self-hosted.js";

const digest = "a".repeat(64);
const manifest: VibecoreManifest = { apiVersion: "vibecore.dev/v1alpha1", kind: "Application", metadata: { name: "safe-app" }, applications: { api: { type: "api", framework: "hono", language: "typescript", path: "apps/api", health: { path: "/health" }, config: { deploymentWorkload: "container", deploymentImage: `ghcr.io/example/api@sha256:${digest}`, port: 3000, hostPort: 8080 } } }, variables: { DATABASE_URL: { required: true, secret: true, applications: ["api"] } }, environments: { dev: { runtime: "local-process" }, staging: { runtime: "self-hosted" }, production: { runtime: "self-hosted", production: true } } };

class RecordingRunner implements DeploymentCommandRunner { calls: Array<{ command: string; args: string[] }> = []; async run(command: string, args: string[]) { this.calls.push({ command, args }); return { exitCode: 0, stdout: "", stderr: "" }; } }

describe("self-hosted Docker deployment", () => {
  it("requires a digest-pinned image, non-root user, and safe remote inputs", () => { const plan = createSelfHostedDockerPlan(manifest, { application: "api", environment: "staging", sourceRevision: "abcdef1234567", host: "app.example.com", user: "vibecore", healthUrl: "https://app.example.com/health" }); expect(plan).toMatchObject({ provider: "self-hosted", mode: "docker-compose", image: `ghcr.io/example/api@sha256:${digest}`, requiredSecretNames: ["DATABASE_URL"] }); expect(plan.compose).toContain("read_only: true"); expect(plan.compose).toContain("no-new-privileges:true"); expect(() => createSelfHostedDockerPlan(manifest, { application: "api", environment: "staging", sourceRevision: "abcdef1234567", host: "app.example.com", user: "root", healthUrl: "https://app.example.com/health" })).toThrow("root"); const mutable = structuredClone(manifest); mutable.applications.api!.config!.deploymentImage = "ghcr.io/example/api:latest"; expect(() => createSelfHostedDockerPlan(mutable, { application: "api", environment: "staging", sourceRevision: "abcdef1234567", host: "app.example.com", user: "vibecore", healthUrl: "https://app.example.com/health" })).toThrow("pinned"); });
  it("requires exact approval before running any remote command", async () => { const plan = createSelfHostedDockerPlan(manifest, { application: "api", environment: "staging", sourceRevision: "abcdef1234567", host: "app.example.com", user: "vibecore", healthUrl: "https://app.example.com/health" }); const runner = new RecordingRunner(); await expect(executeSelfHostedDockerPlan(plan, { approval: "wrong", sshKeyPath: "/keys/deploy", runner })).rejects.toThrow("approval"); expect(runner.calls).toHaveLength(0); });
  it("uses argument arrays, strict SSH, versioned releases, and external health verification", async () => { const plan = createSelfHostedDockerPlan(manifest, { application: "api", environment: "staging", sourceRevision: "abcdef1234567", host: "app.example.com", user: "vibecore", healthUrl: "https://app.example.com/health" }); const runner = new RecordingRunner(); const healthFetch = vi.fn().mockResolvedValue(new Response("secret body is ignored", { status: 200 })); const result = await executeSelfHostedDockerPlan(plan, { approval: plan.digest, sshKeyPath: "/keys/deploy", runner, healthFetch, now: new Date("2026-08-21T00:00:00.000Z") }); expect(result.release.status).toBe("healthy"); expect(runner.calls.some(({ args }) => args.includes("StrictHostKeyChecking=yes"))).toBe(true); expect(runner.calls.some(({ args }) => args.includes("/opt/vibecore/safe-app/releases/abcdef1234567/compose.yaml"))).toBe(true); expect(runner.calls.some(({ args }) => args.includes("--wait"))).toBe(true); expect(JSON.stringify(result)).not.toContain("secret body"); });
  it("requires separate production approval", async () => { const plan = createSelfHostedDockerPlan(manifest, { application: "api", environment: "production", sourceRevision: "abcdef1234567", host: "app.example.com", user: "vibecore", healthUrl: "https://app.example.com/health" }); await expect(executeSelfHostedDockerPlan(plan, { approval: plan.digest, sshKeyPath: "/keys/deploy", runner: new RecordingRunner() })).rejects.toThrow("production approval"); });
  it("applies exact-approved rollback from an existing versioned compose release", async () => { const healthy = { id: "release-good", application: "api", provider: "self-hosted", mode: "docker-compose", environment: "staging", sourceRevision: "1111111", planDigest: "one", status: "healthy" as const, createdAt: "2026-08-20T00:00:00.000Z", updatedAt: "2026-08-20T00:00:00.000Z" }; const failed = { ...healthy, id: "release-bad", sourceRevision: "2222222", planDigest: "two", status: "unhealthy" as const, createdAt: "2026-08-21T00:00:00.000Z", updatedAt: "2026-08-21T00:00:00.000Z" }; const rollback = createRollbackPlan([failed, healthy], failed.id); const runner = new RecordingRunner(); const result = await executeSelfHostedRollback(rollback, [failed, healthy], { approval: rollback.digest, host: "app.example.com", user: "vibecore", remoteRoot: "/opt/vibecore/safe-app", healthUrl: "https://app.example.com/health", sshKeyPath: "/keys/deploy", runner, healthFetch: vi.fn().mockResolvedValue(new Response("ok", { status: 200 })) }); expect(result.failed.status).toBe("rolled-back"); expect(result.release).toMatchObject({ sourceRevision: "1111111", status: "healthy", rollbackOf: "release-bad" }); expect(runner.calls.some(({ args }) => args.includes("/opt/vibecore/safe-app/releases/1111111/compose.yaml"))).toBe(true); });
});
